export enum PLAYER_STATE {
  READY_PLAYER_STATE = 'READY',
  NOTHING_PLAYER_STATE = 'NOTHING',
  TURNING_LEFT_PLAYER_STATE = 'TURNING_LEFT',
  TURNING_RIGHT_PLAYER_STATE = 'TURNING_RIGHT',
  ACCELERATING_PLAYER_STATE = 'ACCELERATING',
  DECELERATING_PLAYER_STATE = 'DECELERATING',
  PICKED_UP_POWERUP_PLAYER_STATE = 'PICKED_UP_POWERUP',
  USED_POWERUP_BOOST_PLAYER_STATE = 'USED_BOOST',
  USED_POWERUP_OIL_PLAYER_STATE = 'USED_OIL',
  HIT_MUD_PLAYER_STATE = 'HIT_MUD',
  HIT_OIL_PLAYER_STAE = 'HIT_OIL',
  FINISHED_PLAYER_STATE = 'FINISHED',
}
